from mysql.connector import connect
from os import path


SEPARADOR = '\\'
endereco = path.dirname(path.realpath(__file__)).removesuffix('model') + 'assets' + SEPARADOR + 'fotos_pokemons' + SEPARADOR
pokemons = (
    (1, 'Bulbassauro', 'Grama', 'Venenoso', endereco + '1.png', 49, 49, 45, 'Um Pokémon planta/veneno com uma semente nas costas.'),
    (2, 'Ivyssauro', 'Grama', 'Venenoso', endereco + '2.png', 63, 62, 60, 'Evolução de Bulbasaur, com uma flor parcialmente aberta.'),
    (3, 'Venussauro', 'Grama', 'Venenoso', endereco + '3.png', 83, 82, 80, 'Evolução final de Bulbasaur, com uma grande flor nas costas.'),
    (4, 'Charmander', 'Fogo', 'NULL', endereco + '4.png', 43, 52, 39, 'Pokémon fogo com uma chama na cauda.'),
    (5, 'Charmeleon', 'Fogo', 'NULL', endereco + '5.png', 58, 64, 58, 'Evolução de Charmander, mais agressivo.'),
    (6, 'Charizard', 'Fogo', 'Voador', endereco + '6.png', 78, 84, 78, 'Evolução final de Charmander, um dragão voador de fogo.'),
    (7, 'Squirtle', 'Água', 'NULL', endereco + '7.png', 65, 48, 44, 'Pokémon aquático parecido com uma tartaruga.'),
    (8, 'Wartortle', 'Água', 'NULL', endereco + '8.png', 80, 63, 59, 'Evolução de Squirtle, com orelhas em forma de asas.'),
    (9, 'Blastoise', 'Água', 'NULL', endereco + '9.png', 100, 83, 79, 'Evolução final de Squirtle, com canhões de água no casco.'),
    (10, 'Caterpie', 'Inseto', 'NULL', endereco + '10.png', 35, 30, 45, 'Um Pokémon inseto verde e pequeno.'),
    (11, 'Metapod', 'Inseto', 'NULL', endereco + '11.png', 55, 20, 50, 'Evolução de Caterpie, em forma de casulo.'),
    (12, 'Butterfree', 'Inseto', 'Voador', endereco + '12.png', 50, 45, 60, 'Evolução final de Caterpie, uma borboleta colorida.'),
    (13, 'Weedle', 'Inseto', 'Venenoso', endereco + '13.png', 30, 35, 40, 'Um Pokémon inseto com um chifre afiado.'),
    (14, 'Kakuna', 'Inseto', 'Venenoso', endereco + '14.png', 50, 25, 45, 'Evolução de Weedle, em forma de casulo.'),
    (15, 'Beedrill', 'Inseto', 'Venenoso', endereco + '15.png', 40, 90, 65, 'Evolução final de Weedle, uma vespa com ferrões.'),
    (16, 'Pidgey', 'Normal', 'Voador', endereco + '16.png', 40, 45, 40, 'Um Pokémon pássaro pequeno e comum.'),
    (17, 'Pidgeotto', 'Normal', 'Voador', endereco + '17.png', 55, 60, 63, 'Evolução de Pidgey, maior e mais forte.'),
    (18, 'Pidgeot', 'Normal', 'Voador', endereco + '18.png', 75, 80, 83, 'Evolução final de Pidgey, um pássaro majestoso.'),
    (19, 'Rattata', 'Normal', 'NULL', endereco + '19.png', 35, 56, 30, 'Um Pokémon rato, rápido e ágil.'),
    (20, 'Raticate', 'Normal', 'NULL', endereco + '20.png', 60, 81, 55, 'Evolução de Rattata, com grandes dentes.'),
    (21, 'Spearow', 'Normal', 'Voador', endereco + '21.png', 30, 60, 40, 'Um pequeno Pokémon pássaro agressivo.'),
    (22, 'Fearow', 'Normal', 'Voador', endereco + '22.png', 65, 90, 65, 'Evolução de Spearow, um grande pássaro predador.'),
    (23, 'Ekans', 'Venenoso', 'NULL', endereco + '23.png', 44, 60, 35, 'Um Pokémon cobra venenosa.'),
    (24, 'Arbok', 'Venenoso', 'NULL', endereco + '24.png', 69, 85, 60, 'Evolução de Ekans, com padrões assustadores em seu corpo.'),
    (25, 'Pikachu', 'Elétrico', 'NULL', endereco + '25.png', 40, 55, 35, 'Um Pokémon elétrico famoso, com bochechas que geram eletricidade.'),
    (26, 'Raichu', 'Elétrico', 'NULL', endereco + '26.png', 55, 90, 60, 'Evolução de Pikachu, mais poderoso eletricamente.'),
    (27, 'Sandshrew', 'Terrestre', 'NULL', endereco + '27.png', 85, 75, 50, 'Um Pokémon de terra que cava tocas.'),
    (28, 'Sandslash', 'Terrestre', 'NULL', endereco + '28.png', 110, 100, 75, 'Evolução de Sandshrew, com garras afiadas.'),
    (29, 'NidoranF', 'Venenoso', 'NULL', endereco + '29.png', 52, 47, 55, 'Um Pokémon venenoso pequeno.'),
    (30, 'Nidorina', 'Venenoso', 'NULL', endereco + '30.png', 67, 62, 70, 'Evolução de NidoranF, mais forte e resistente.'),
    (31, 'Nidoqueen', 'Venenoso', 'Terrestre', endereco + '31.png', 87, 92, 90, 'Evolução final de NidoranF, muito poderosa.'),
    (32, 'NidoranM', 'Venenoso', 'NULL', endereco + '32.png', 40, 57, 46, 'Versão masculina de Nidoran, também venenoso.'),
    (33, 'Nidorino', 'Venenoso', 'NULL', endereco + '33.png', 57, 72, 61, 'Evolução de NidoranM, mais robusto.'),
    (34, 'Nidoking', 'Venenoso', 'Terrestre', endereco + '34.png', 77, 102, 81, 'Evolução final de NidoranM, muito forte.'),
    (35, 'Clefairy', 'Fada', 'NULL', endereco + '35.png', 48, 45, 70, 'Um Pokémon fada que adora a lua.'),
    (36, 'Clefable', 'Fada', 'NULL', endereco + '36.png', 73, 70, 95, 'Evolução de Clefairy, com poderes mágicos.'),
    (37, 'Vulpix', 'Fogo', 'NULL', endereco + '37.png', 40, 41, 38, 'Um Pokémon raposa de fogo.'),
    (38, 'Ninetales', 'Fogo', 'NULL', endereco + '38.png', 75, 76, 73, 'Evolução de Vulpix, com nove caudas.'),
    (39, 'Jigglypuff', 'Normal', 'Fada', endereco + '39.png', 20, 45, 115, 'Um Pokémon fada que canta para fazer os outros dormirem.'),
    (40, 'Wigglytuff', 'Normal', 'Fada', endereco + '40.png', 45, 70, 140, 'Evolução de Jigglypuff, com habilidades semelhantes.'),
    (41, 'Zubat', 'Venenoso', 'Voador', endereco + '41.png', 35, 45, 40, 'Um Pokémon morcego que usa ultrassom.'),
    (42, 'Golbat', 'Venenoso', 'Voador', endereco + '42.png', 70, 80, 75, 'Evolução de Zubat, com habilidades de voo aprimoradas.'),
    (43, 'Oddish', 'Grama', 'Venenoso', endereco + '43.png', 55, 75, 45, 'Um Pokémon planta/veneno que se parece com uma erva daninha.'),
    (44, 'Gloom', 'Grama', 'Venenoso', endereco + '44.png', 70, 85, 60, 'Evolução de Oddish, com um odor forte.'),
    (45, 'Vileplume', 'Grama', 'Venenoso', endereco + '45.png', 85, 110, 75, 'Evolução final de Oddish, com uma flor grande e tóxica.'),
    (46, 'Paras', 'Inseto', 'Grama', endereco + '46.png', 55, 70, 35, 'Um Pokémon inseto/planta com cogumelos nas costas.'),
    (47, 'Parasect', 'Inseto', 'Grama', endereco + '47.png', 80, 95, 60, 'Evolução de Paras, dominado pelos cogumelos.'),
    (48, 'Venonat', 'Inseto', 'Venenoso', endereco + '48.png', 50, 55, 60, 'Um Pokémon inseto com olhos grandes.'),
    (49, 'Venomoth', 'Inseto', 'Venenoso', endereco + '49.png', 60, 65, 70, 'Evolução de Venonat, um inseto voador.'),
    (50, 'Diglett', 'Terrestre', 'NULL', endereco + '50.png', 25, 55, 10, 'Um Pokémon de terra que vive subterrâneo.'),
    (51, 'Dugtrio', 'Terrestre', 'NULL', endereco + '51.png', 50, 100, 35, 'Evolução de Diglett, composto por três Digletts.'),
    (52, 'Meowth', 'Normal', 'NULL', endereco + '52.png', 35, 45, 40, 'Um Pokémon gato que anda sobre duas patas.'),
    (53, 'Persian', 'Normal', 'NULL', endereco + '53.png', 60, 70, 65, 'Evolução de Meowth, elegante e rápido.'),
    (54, 'Psyduck', 'Água', 'NULL', endereco + '54.png', 50, 52, 50, 'Um Pokémon aquático com dores de cabeça constantes.'),
    (55, 'Golduck', 'Água', 'NULL', endereco + '55.png', 75, 82, 80, 'Evolução de Psyduck, mais ágil e poderoso.'),
    (56, 'Mankey', 'Lutador', 'NULL', endereco + '56.png', 35, 80, 40, 'Um Pokémon macaco agressivo.'),
    (57, 'Primeape', 'Lutador', 'NULL', endereco + '57.png', 60, 105, 65, 'Evolução de Mankey, ainda mais feroz.'),
    (58, 'Growlithe', 'Fogo', 'NULL', endereco + '58.png', 45, 70, 55, 'Um Pokémon cachorro de fogo.'),
    (59, 'Arcanine', 'Fogo', 'NULL', endereco + '59.png', 80, 110, 90, 'Evolução de Growlithe, majestoso e poderoso.'),
    (60, 'Poliwag', 'Água', 'NULL', endereco + '60.png', 40, 50, 40, 'Um Pokémon aquático redondo com uma espiral na barriga.'),
    (61, 'Poliwhirl', 'Água', 'NULL', endereco + '61.png', 65, 65, 65, 'Evolução de Poliwag, mais desenvolvido.'),
    (62, 'Poliwrath', 'Água', 'Lutador', endereco + '62.png', 95, 95, 90, 'Evolução final de Poliwag, forte e resistente.'),
    (63, 'Abra', 'Psíquico', 'NULL', endereco + '63.png', 15, 20, 25, 'Um Pokémon psíquico que frequentemente teletransporta.'),
    (64, 'Kadabra', 'Psíquico', 'NULL', endereco + '64.png', 30, 35, 40, 'Evolução de Abra, com habilidades psíquicas avançadas.'),
    (65, 'Alakazam', 'Psíquico', 'NULL', endereco + '65.png', 45, 50, 55, 'Evolução final de Abra, com inteligência excepcional.'),
    (66, 'Machop', 'Lutador', 'NULL', endereco + '66.png', 50, 80, 70, 'Um Pokémon lutador que adora treinar.'),
    (67, 'Machoke', 'Lutador', 'NULL', endereco + '67.png', 70, 100, 80, 'Evolução de Machop, com mais músculos.'),
    (68, 'Machamp', 'Lutador', 'NULL', endereco + '68.png', 80, 130, 90, 'Evolução final de Machop, com quatro braços poderosos.'),
    (69, 'Bellsprout', 'Grama', 'Venenoso', endereco + '69.png', 35, 75, 50, 'Um Pokémon planta/veneno com um corpo fino.'),
    (70, 'Weepinbell', 'Grama', 'Venenoso', endereco + '70.png', 50, 90, 65, 'Evolução de Bellsprout, com uma boca grande.'),
    (71, 'Victreebel', 'Grama', 'Venenoso', endereco + '71.png', 65, 105, 80, 'Evolução final de Bellsprout, carnívoro e perigoso.'),
    (72, 'Tentacool', 'Água', 'Venenoso', endereco + '72.png', 35, 40, 40, 'Um Pokémon aquático venenoso com tentáculos.'),
    (73, 'Tentacruel', 'Água', 'Venenoso', endereco + '73.png', 65, 70, 80, 'Evolução de Tentacool, com mais tentáculos e mais perigoso.'),
    (74, 'Geodude', 'Pedra', 'Terrestre', endereco + '74.png', 100, 80, 40, 'Um Pokémon rocha que se camufla como pedra.'),
    (75, 'Graveler', 'Pedra', 'Terrestre', endereco + '75.png', 115, 95, 55, 'Evolução de Geodude, com quatro braços.'),
    (76, 'Golem', 'Pedra', 'Terrestre', endereco + '76.png', 130, 110, 80, 'Evolução final de Geodude, com uma carapaça rochosa.'),
    (77, 'Ponyta', 'Fogo', 'NULL', endereco + '77.png', 55, 85, 50, 'Um Pokémon cavalo de fogo com uma crina flamejante.'),
    (78, 'Rapidash', 'Fogo', 'NULL', endereco + '78.png', 70, 100, 65, 'Evolução de Ponyta, ainda mais rápido e majestoso.'),
    (79, 'Slowpoke', 'Água', 'Psíquico', endereco + '79.png', 65, 65, 90, 'Um Pokémon aquático/psíquico preguiçoso.'),
    (80, 'Slowbro', 'Água', 'Psíquico', endereco + '80.png', 110, 75, 95, 'Evolução de Slowpoke, com uma concha mordendo sua cauda.'),
    (81, 'Magnemite', 'Elétrico', 'Aço', endereco + '81.png', 95, 35, 25, 'Um Pokémon elétrico/metálico com imãs.'),
    (82, 'Magneton', 'Elétrico', 'Aço', endereco + '82.png', 120, 60, 50, 'Evolução de Magnemite, composto por três Magnemites.'),
    (83, "Farfetch'd", 'Normal', 'Voador', endereco + '83.png', 55, 65, 52, 'Um Pokémon pássaro que carrega um alho-poró.'),
    (84, 'Doduo', 'Normal', 'Voador', endereco + '84.png', 45, 85, 35, 'Um Pokémon pássaro de duas cabeças.'),
    (85, 'Dodrio', 'Normal', 'Voador', endereco + '85.png', 70, 110, 60, 'Evolução de Doduo, com três cabeças.'),
    (86, 'Seel', 'Água', 'NULL', endereco + '86.png', 55, 45, 65, 'Um Pokémon aquático semelhante a uma foca.'),
    (87, 'Dewgong', 'Água', 'Gelo', endereco + '87.png', 80, 70, 90, 'Evolução de Seel, com uma aparência mais elegante.'),
    (88, 'Grimer', 'Venenoso', 'NULL', endereco + '88.png', 50, 80, 80, 'Um Pokémon de lama venenosa.'),
    (89, 'Muk', 'Venenoso', 'NULL', endereco + '89.png', 75, 105, 105, 'Evolução de Grimer, ainda mais tóxico.'),
    (90, 'Shellder', 'Água', 'NULL', endereco + '90.png', 180, 65, 30, 'Um Pokémon de água com uma concha dura.'),
    (91, 'Cloyster', 'Água', 'Gelo', endereco + '91.png', 180, 95, 50, 'Evolução de Shellder, com uma concha mais robusta.'),
    (92, 'Gastly', 'Fantasma', 'Venenoso', endereco + '92.png', 35, 35, 30, 'Um Pokémon fantasma/gás.'),
    (93, 'Haunter', 'Fantasma', 'Venenoso', endereco + '93.png', 55, 50, 45, 'Evolução de Gastly, com uma forma mais definida.'),
    (94, 'Gengar', 'Fantasma', 'Venenoso', endereco + '94.png', 60, 65, 60, 'Evolução final de Gastly, com habilidades de fantasma aprimoradas.'),
    (95, 'Onix', 'Pedra', 'Terrestre', endereco + '95.png', 160, 45, 35, 'Um Pokémon rocha/terra em forma de serpente.'),
    (96, 'Drowzee', 'Psíquico', 'NULL', endereco + '96.png', 45, 48, 60, 'Um Pokémon psíquico que adora sonhos.'),
    (97, 'Hypno', 'Psíquico', 'NULL', endereco + '97.png', 70, 73, 85, 'Evolução de Drowzee, com habilidades hipnóticas.'),
    (98, 'Krabby', 'Água', 'NULL', endereco + '98.png', 105, 105, 30, 'Um Pokémon caranguejo aquático.'),
    (99, 'Kingler', 'Água', 'NULL', endereco + '99.png', 115, 130, 55, 'Evolução de Krabby, com uma pinça maior.'),
    (100, 'Voltorb', 'Elétrico', 'NULL', endereco + '100.png', 50, 30, 40, 'Um Pokémon elétrico em forma de Poké Bola.'),
    (101, 'Electrode', 'Elétrico', 'NULL', endereco + '101.png', 70, 50, 60, 'Evolução de Voltorb, ainda mais elétrico.'),
    (102, 'Exeggcute', 'Grama', 'Psíquico', endereco + '102.png', 80, 40, 60, 'Um conjunto de ovos psíquicos/planta.'),
    (103, 'Exeggutor', 'Grama', 'Psíquico', endereco + '103.png', 95, 95, 95, 'Evolução de Exeggcute, um coqueiro psíquico.'),
    (104, 'Cubone', 'Terrestre', 'NULL', endereco + '104.png', 95, 50, 50, 'Um Pokémon que usa o crânio de sua mãe como capcete.'),
    (105, 'Marowak', 'Terrestre', 'NULL', endereco + '105.png', 110, 80, 60, 'Evolução de Cubone, empunha um osso como arma.'),
    (106, 'Hitmonlee', 'Lutador', 'NULL', endereco + '106.png', 53, 120, 50, 'Um Pokémon lutador especialista em chutes.'),
    (107, 'Hitmonchan', 'Lutador', 'NULL', endereco + '107.png', 79, 105, 50, 'Um Pokémon lutador especializado em socos.'),
    (108, 'Lickitung', 'Normal', 'NULL', endereco + '108.png', 75, 55, 90, 'Um Pokémon com uma língua muito comprida.'),
    (109, 'Koffing', 'Venenoso', 'NULL', endereco + '109.png', 95, 65, 40, 'Um Pokémon de gás venenoso, flutuante.'),
    (110, 'Weezing', 'Venenoso', 'NULL', endereco + '110.png', 120, 90, 65, 'Evolução de Koffing, com duas cabeças e mais gás venenoso.'),
    (111, 'Rhyhorn', 'Terrestre', 'Pedra', endereco + '111.png', 95, 85, 80, 'Um Pokémon de rocha/terra parecido com um rinoceronte.'),
    (112, 'Rhydon', 'Terrestre', 'Pedra', endereco + '112.png', 120, 130, 105, 'Evolução de Rhyhorn, mais robusto e poderoso.'),
    (113, 'Chansey', 'Normal', 'NULL', endereco + '113.png', 5, 5, 250, 'Um Pokémon que carrega um ovo que tem propriedades curativas.'),
    (114, 'Tangela', 'Grama', 'NULL', endereco + '114.png', 115, 55, 65, 'Um Pokémon planta coberto de vinhas azuis.'),
    (115, 'Kangaskhan', 'Normal', 'NULL', endereco + '115.png', 80, 95, 105, 'Um Pokémon que cuida de seu filhote no marsúpio.'),
    (116, 'Horsea', 'Água', 'NULL', endereco + '116.png', 70, 40, 30, 'Um Pokémon aquático que se parece com um cavalo-marinho.'),
    (117, 'Seadra', 'Água', 'NULL', endereco + '117.png', 95, 65, 55, 'Evolução de Horsea, com espinhos afiados.'),
    (118, 'Goldeen', 'Água', 'NULL', endereco + '118.png', 60, 67, 45, 'Um Pokémon peixe com uma barbatana dorsal parecida com um chifre.'),
    (119, 'Seaking', 'Água', 'NULL', endereco + '119.png', 65, 92, 80, 'Evolução de Goldeen, maior e mais colorido.'),
    (120, 'Staryu', 'Água', 'NULL', endereco + '120.png', 85, 45, 30, 'Um Pokémon estrela-do-mar com um núcleo vermelho.'),
    (121, 'Starmie', 'Água', 'Psíquico', endereco + '121.png', 85, 75, 60, 'Evolução de Staryu, com um núcleo mais brilhante.'),
    (122, 'Mr. Mime', 'Psíquico', 'Fada', endereco + '122.png', 65, 45, 40, 'Um Pokémon psíquico que cria barreiras invisíveis.'),
    (123, 'Scyther', 'Inseto', 'Voador', endereco + '123.png', 80, 110, 70, 'Um Pokémon inseto/voador com lâminas afiadas nos braços.'),
    (124, 'Jynx', 'Gelo', 'Psíquico', endereco + '124.png', 35, 50, 65, 'Um Pokémon psíquico/gelo que se parece com uma dançarina.'),
    (125, 'Electabuzz', 'Elétrico', 'NULL', endereco + '125.png', 57, 83, 65, 'Um Pokémon elétrico com habilidades de gerar eletricidade.'),
    (126, 'Magmar', 'Fogo', 'NULL', endereco + '126.png', 57, 95, 65, 'Um Pokémon fogo com um corpo flamejante.'),
    (127, 'Pinsir', 'Inseto', 'NULL', endereco + '127.png', 100, 125, 65, 'Um Pokémon inseto com pinças poderosas.'),
    (128, 'Tauros', 'Normal', 'NULL', endereco + '128.png', 95, 100, 75, 'Um Pokémon boi que ataca com seus chifres.'),
    (129, 'Magikarp', 'Água', 'NULL', endereco + '129.png', 55, 10, 20, 'Um Pokémon peixe que é notoriamente fraco.'),
    (130, 'Gyarados', 'Água', 'Voador', endereco + '130.png', 79, 125, 95, 'Evolução de Magikarp, um poderoso Pokémon serpente de água/voador.'),
    (131, 'Lapras', 'Água', 'Gelo', endereco + '131.png', 80, 85, 130, 'Um Pokémon aquático/gelo que adora navegar com pessoas nas costas.'),
    (132, 'Ditto', 'Normal', 'NULL', endereco + '132.png', 48, 48, 48, 'Um Pokémon que pode se transformar em qualquer outro Pokémon.'),
    (133, 'Eevee', 'Normal', 'NULL', endereco + '133.png', 50, 55, 55, 'Um Pokémon conhecido por suas múltiplas evoluções.'),
    (134, 'Vaporeon', 'Água', 'NULL', endereco + '134.png', 60, 65, 130, 'Evolução de Eevee, um Pokémon água.'),
    (135, 'Jolteon', 'Elétrico', 'NULL', endereco + '135.png', 60, 65, 65, 'Evolução de Eevee, um Pokémon elétrico.'),
    (136, 'Flareon', 'Fogo', 'NULL', endereco + '136.png', 60, 130, 65, 'Evolução de Eevee, um Pokémon fogo.'),
    (137, 'Porygon', 'Normal', 'NULL', endereco + '137.png', 70, 60, 65, 'Um Pokémon feito de dados e gráficos.'),
    (138, 'Omanyte', 'Pedra', 'Água', endereco + '138.png', 100, 40, 35, 'Um Pokémon fóssil aquático.'),
    (139, 'Omastar', 'Pedra', 'Água', endereco + '139.png', 125, 60, 70, 'Evolução de Omanyte, com tentáculos e uma concha espiral.'),
    (140, 'Kabuto', 'Pedra', 'Água', endereco + '140.png', 90, 80, 30, 'Um Pokémon fóssil com uma carapaça protetora.'),
    (141, 'Kabutops', 'Pedra', 'Água', endereco + '141.png', 105, 115, 60, 'Evolução de Kabuto, com lâminas afiadas.'),
    (142, 'Aerodactyl', 'Pedra', 'Voador', endereco + '142.png', 65, 105, 80, 'Um Pokémon fóssil voador.'),
    (143, 'Snorlax', 'Normal', 'NULL', endereco + '143.png', 65, 110, 160, 'Um Pokémon gigante e preguiçoso.'),
    (144, 'Articuno', 'Gelo', 'Voador', endereco + '144.png', 100, 85, 90, 'Um Pokémon lendário de gelo/voador.'),
    (145, 'Zapdos', 'Elétrico', 'Voador', endereco + '145.png', 85, 90, 90, 'Um Pokémon lendário elétrico/voador.'),
    (146, 'Moltres', 'Fogo', 'Voador', endereco + '146.png', 90, 100, 90, 'Um Pokémon lendário de fogo/voador.'),
    (147, 'Dratini', 'Dragão', 'NULL', endereco + '147.png', 50, 64, 41, 'Um Pokémon dragão aquático.'),
    (148, 'Dragonair', 'Dragão', 'NULL', endereco + '148.png', 70, 84, 61, 'Evolução de Dratini, elegante e serpenteante.'),
    (149, 'Dragonite', 'Dragão', 'Voador', endereco + '149.png', 95, 134, 91, 'Evolução final de Dratini, um dragão poderoso.'),
    (150, 'Mewtwo', 'Psíquico', 'NULL', endereco + '150.png', 90, 110, 106, 'Um Pokémon psíquico, resultado de um experimento genético.'),
    (151, 'Mew', 'Psíquico', 'NULL', endereco + '151.png', 100, 100, 100, 'Um Pokémon psíquico mítico, conhecido por sua raridade.'),)

banco = connect(
  host="localhost",
  user="root",
  password="",
  database="Pokedex"
)
cursor = banco.cursor()
for pokemon in pokemons:
    pokemon = tuple(pokemon)
    cursor.execute('insert into tb_pokemons (id, nome, tipo_1, tipo_2, foto, ataque, defesa, hp, descrição) values (%s, %s, %s, %s, %s, %s, %s, %s, %s);', pokemon)
banco.commit()
cursor.close()
banco.close()
