from mysql.connector import connect
from os import path

endereco = path.dirname(path.realpath(__file__))
pokemons = [
    [1, 'Bulbassauro', 'Grama', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\1.png', 5, 5, 5, 'descrição'],
    [2, 'Ivyssauro', 'Grama', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\2.png', 5, 5, 5, 'descrição'],
    [3, 'Venussauro', 'Grama', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\3.png', 5, 5, 5, 'descrição'],
    [4, 'Charmander', 'Fogo', 'NULL', endereco.removesuffix('model') + 'assets\\\\4.png', 5, 5, 'descrição'],
    [5, 'Charmeleon', 'Fogo', 'NULL', endereco.removesuffix('model') + 'assets\\\\5.png', 5, 5, 5, 'descrição'],
    [6, 'Charizard', 'Fogo', 'Voador', endereco.removesuffix('model') + 'assets\\\\6.png', 5, 5, 5, 'descrição'],
    [7, 'Squirtle', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\7.png', 5, 5, 5, 'descrição'],
    [8, 'Wartortle', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\8.png', 5, 5, 5, 'descrição'],
    [9, 'Blastoise', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\9.png', 5, 5, 5, 'descrição'],
    [10, 'Caterpie', 'Inseto', 'NULL', endereco.removesuffix('model') + 'assets\\\\10.png', 5, 5, 5, 'descrição'],
    [11, 'Metapod', 'Inseto', 'NULL', endereco.removesuffix('model') + 'assets\\\\11.png', 5, 5, 5, 'descrição'],
    [12, 'Butterfree', 'Inseto', 'Voador', endereco.removesuffix('model') + 'assets\\\\12.png', 5, 5, 5, 'descrição'],
    [13, 'Weedle', 'Inseto', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\13.png', 5, 5, 5, 'descrição'],
    [14, 'Kakuna', 'Inseto', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\14.png', 5, 5, 5, 'descrição'],
    [15, 'Beedrill', 'Inseto', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\15.png', 5, 5, 5, 'descrição'],
    [16, 'Pidgey', 'Normal', 'Voador', endereco.removesuffix('model') + 'assets\\\\16.png', 5, 5, 5, 'descrição'],
    [17, 'Pidgeotto', 'Normal', 'Voador', endereco.removesuffix('model') + 'assets\\\\17.png', 5, 5, 5, 'descrição'],
    [18, 'Pidgeot', 'Normal', 'Voador', endereco.removesuffix('model') + 'assets\\\\18.png', 5, 5, 5, 'descrição'],
    [19, 'Rattata', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\19.png', 5, 5, 5, 'descrição'],
    [20, 'Raticate', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\20.png', 5, 5, 5, 'descrição'],
    [21, 'Spearow', 'Normal', 'Voador', endereco.removesuffix('model') + 'assets\\\\21.png', 5, 5, 5, 'descrição'],
    [22, 'Fearow', 'Normal', 'Voador', endereco.removesuffix('model') + 'assets\\\\22.png', 5, 5, 5, 'descrição'],
    [23, 'Ekans', 'Venenoso', 'NULL', endereco.removesuffix('model') + 'assets\\\\23.png', 5, 5, 5, 'descrição'],
    [24, 'Arbok', 'Venenoso', 'NULL', endereco.removesuffix('model') + 'assets\\\\24.png', 5, 5, 5, 'descrição'],
    [25, 'Pikachu', 'Elétrico', 'NULL', endereco.removesuffix('model') + 'assets\\\\25.png', 5, 5, 5, 'descrição'],
    [26, 'Raichu', 'Elétrico', 'NULL', endereco.removesuffix('model') + 'assets\\\\26.png', 5, 5, 5, 'descrição'],
    [27, 'Sandshrew', 'Terrestre', 'NULL', endereco.removesuffix('model') + 'assets\\\\27.png', 5, 5, 5, 'descrição'],
    [28, 'Sandslash', 'Terrestre', 'NULL', endereco.removesuffix('model') + 'assets\\\\28.png', 5, 5, 5, 'descrição'],
    [29, 'Nidoran♀', 'Venenoso', 'NULL', endereco.removesuffix('model') + 'assets\\\\29.png', 5, 5, 5, 'descrição'],
    [30, 'Nidorina', 'Venenoso', 'NULL', endereco.removesuffix('model') + 'assets\\\\30.png', 5, 5, 5, 'descrição'],
    [31, 'Nidoqueen', 'Venenoso', 'Terrestre', endereco.removesuffix('model') + 'assets\\\\31.png', 5, 5, 5, 'descrição'],
    [32, 'Nidoran♂', 'Venenoso', 'NULL', endereco.removesuffix('model') + 'assets\\\\32.png', 5, 5, 5, 'descrição'],
    [33, 'Nidorino', 'Venenoso', 'NULL', endereco.removesuffix('model') + 'assets\\\\33.png', 5, 5, 5, 'descrição'],
    [34, 'Nidoking', 'Venenoso', 'Terrestre', endereco.removesuffix('model') + 'assets\\\\34.png', 5, 5, 5, 'descrição'],
    [35, 'Clefairy', 'Fada', 'NULL', endereco.removesuffix('model') + 'assets\\\\35.png', 5, 5, 5, 'descrição'],
    [36, 'Clefable', 'Fada', 'NULL', endereco.removesuffix('model') + 'assets\\\\36.png', 5, 5, 5, 'descrição'],
    [37, 'Vulpix', 'Fogo', 'NULL', endereco.removesuffix('model') + 'assets\\\\37.png', 5, 5, 5, 'descrição'],
    [38, 'Ninetales', 'Fogo', 'NULL', endereco.removesuffix('model') + 'assets\\\\38.png', 5, 5, 5, 'descrição'],
    [39, 'Jigglypuff', 'Normal', 'Fada', endereco.removesuffix('model') + 'assets\\\\39.png', 5, 5, 5, 'descrição'],
    [40, 'Wigglytuff', 'Normal', 'Fada', endereco.removesuffix('model') + 'assets\\\\40.png', 5, 5, 5, 'descrição'],
    [41, 'Zubat', 'Venenoso', 'Voador', endereco.removesuffix('model') + 'assets\\\\41.png', 5, 5, 5, 'descrição'],
    [42, 'Golbat', 'Venenoso', 'Voador', endereco.removesuffix('model') + 'assets\\\\42.png', 5, 5, 5, 'descrição'],
    [43, 'Oddish', 'Grama', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\43.png', 5, 5, 5, 'descrição'],
    [44, 'Gloom', 'Grama', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\44.png', 5, 5, 5, 'descrição'],
    [45, 'Vileplume', 'Grama', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\45.png', 5, 5, 5, 'descrição'],
    [46, 'Paras', 'Inseto', 'Grama', endereco.removesuffix('model') + 'assets\\\\46.png', 5, 5, 5, 'descrição'],
    [47, 'Parasect', 'Inseto', 'Grama', endereco.removesuffix('model') + 'assets\\\\47.png', 5, 5, 5, 'descrição'],
    [48, 'Venonat', 'Inseto', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\48.png', 5, 5, 5, 'descrição'],
    [49, 'Venomoth', 'Inseto', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\49.png', 5, 5, 5, 'descrição'],
    [50, 'Diglett', 'Terrestre', 'NULL', endereco.removesuffix('model') + 'assets\\\\50.png', 5, 5, 5, 'descrição'],
    [51, 'Dugtrio', 'Terrestre', 'NULL', endereco.removesuffix('model') + 'assets\\\\51.png', 5, 5, 5, 'descrição'],
    [52, 'Meowth', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\52.png', 5, 5, 5, 'descrição'],
    [53, 'Persian', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\53.png', 5, 5, 5, 'descrição'],
    [54, 'Psyduck', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\54.png', 5, 5, 5, 'descrição'],
    [55, 'Golduck', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\55.png', 5, 5, 5, 'descrição'],
    [56, 'Mankey', 'Lutador', 'NULL', endereco.removesuffix('model') + 'assets\\\\56.png', 5, 5, 5, 'descrição'],
    [57, 'Primeape', 'Lutador', 'NULL', endereco.removesuffix('model') + 'assets\\\\57.png', 5, 5, 5, 'descrição'],
    [58, 'Growlithe', 'Fogo', 'NULL', endereco.removesuffix('model') + 'assets\\\\58.png', 5, 5, 5, 'descrição'],
    [59, 'Arcanine', 'Fogo', 'NULL', endereco.removesuffix('model') + 'assets\\\\59.png', 5, 5, 5, 'descrição'],
    [60, 'Poliwag', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\60.png', 5, 5, 5, 'descrição'],
    [61, 'Poliwhirl', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\61.png', 5, 5, 5, 'descrição'],
    [62, 'Poliwrath', 'Água', 'Lutador', endereco.removesuffix('model') + 'assets\\\\62.png', 5, 5, 5, 'descrição'],
    [63, 'Abra', 'Psíquico', 'NULL', endereco.removesuffix('model') + 'assets\\\\63.png', 5, 5, 5, 'descrição'],
    [64, 'Kadabra', 'Psíquico', 'NULL', endereco.removesuffix('model') + 'assets\\\\64.png', 5, 5, 5, 'descrição'],
    [65, 'Alakazam', 'Psíquico', 'NULL', endereco.removesuffix('model') + 'assets\\\\65.png', 5, 5, 5, 'descrição'],
    [66, 'Machop', 'Lutador', 'NULL', endereco.removesuffix('model') + 'assets\\\\66.png', 5, 5, 5, 'descrição'],
    [67, 'Machoke', 'Lutador', 'NULL', endereco.removesuffix('model') + 'assets\\\\67.png', 5, 5, 5, 'descrição'],
    [68, 'Machamp', 'Lutador', 'NULL', endereco.removesuffix('model') + 'assets\\\\68.png', 5, 5, 5, 'descrição'],
    [69, 'Bellsprout', 'Grama', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\69.png', 5, 5, 5, 'descrição'],
    [70, 'Weepinbell', 'Grama', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\70.png', 5, 5, 5, 'descrição'],
    [71, 'Victreebel', 'Grama', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\71.png', 5, 5, 5, 'descrição'],
    [72, 'Tentacool', 'Água', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\72.png', 5, 5, 5, 'descrição'],
    [73, 'Tentacruel', 'Água', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\73.png', 5, 5, 5, 'descrição'],
    [74, 'Geodude', 'Pedra', 'Terrestre', endereco.removesuffix('model') + 'assets\\\\74.png', 5, 5, 5, 'descrição'],
    [75, 'Graveler', 'Pedra', 'Terrestre', endereco.removesuffix('model') + 'assets\\\\75.png', 5, 5, 5, 'descrição'],
    [76, 'Golem', 'Pedra', 'Terrestre', endereco.removesuffix('model') + 'assets\\\\76.png', 5, 5, 5, 'descrição'],
    [77, 'Ponyta', 'Fogo', 'NULL', endereco.removesuffix('model') + 'assets\\\\77.png', 5, 5, 5, 'descrição'],
    [78, 'Rapidash', 'Fogo', 'NULL', endereco.removesuffix('model') + 'assets\\\\78.png', 5, 5, 5, 'descrição'],
    [79, 'Slowpoke', 'Água', 'Psíquico', endereco.removesuffix('model') + 'assets\\\\79.png', 5, 5, 5, 'descrição'],
    [80, 'Slowbro', 'Água', 'Psíquico', endereco.removesuffix('model') + 'assets\\\\80.png', 5, 5, 5, 'descrição'],
    [81, 'Magnemite', 'Elétrico', 'Aço', endereco.removesuffix('model') + 'assets\\\\81.png', 5, 5, 5, 'descrição'],
    [82, 'Magneton', 'Elétrico', 'Aço', endereco.removesuffix('model') + 'assets\\\\82.png', 5, 5, 5, 'descrição'],
    [83, "Farfetch'd", 'Normal', 'Voador', endereco.removesuffix('model') + 'assets\\\\83.png', 5, 5, 5, 'descrição'],
    [84, 'Doduo', 'Normal', 'Voador', endereco.removesuffix('model') + 'assets\\\\84.png', 5, 5, 5, 'descrição'],
    [85, 'Dodrio', 'Normal', 'Voador', endereco.removesuffix('model') + 'assets\\\\85.png', 5, 5, 5, 'descrição'],
    [86, 'Seel', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\86.png', 5, 5, 5, 'descrição'],
    [87, 'Dewgong', 'Água', 'Gelo', endereco.removesuffix('model') + 'assets\\\\87.png', 5, 5, 5, 'descrição'],
    [88, 'Grimer', 'Venenoso', 'NULL', endereco.removesuffix('model') + 'assets\\\\88.png', 5, 5, 5, 'descrição'],
    [89, 'Muk', 'Venenoso', 'NULL', endereco.removesuffix('model') + 'assets\\\\89.png', 5, 5, 5, 'descrição'],
    [90, 'Shellder', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\90.png', 5, 5, 5, 'descrição'],
    [91, 'Cloyster', 'Água', 'Gelo', endereco.removesuffix('model') + 'assets\\\\91.png', 5, 5, 5, 'descrição'],
    [92, 'Gastly', 'Fantasma', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\92.png', 5, 5, 5, 'descrição'],
    [93, 'Haunter', 'Fantasma', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\93.png', 5, 5, 5, 'descrição'],
    [94, 'Gengar', 'Fantasma', 'Venenoso', endereco.removesuffix('model') + 'assets\\\\94.png', 5, 5, 5, 'descrição'],
    [95, 'Onix', 'Pedra', 'Terrestre', endereco.removesuffix('model') + 'assets\\\\95.png', 5, 5, 5, 'descrição'],
    [96, 'Drowzee', 'Psíquico', 'NULL', endereco.removesuffix('model') + 'assets\\\\96.png', 5, 5, 5, 'descrição'],
    [97, 'Hypno', 'Psíquico', 'NULL', endereco.removesuffix('model') + 'assets\\\\97.png', 5, 5, 5, 'descrição'],
    [98, 'Krabby', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\98.png', 5, 5, 5, 'descrição'],
    [99, 'Kingler', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\99.png', 5, 5, 5, 'descrição'],
    [100, 'Voltorb', 'Elétrico', 'NULL', endereco.removesuffix('model') + 'assets\\\\100.png', 5, 5, 5, 'descrição'],
    [101, 'Electrode', 'Elétrico', 'NULL', endereco.removesuffix('model') + 'assets\\\\101.png', 5, 5, 5, 'descrição'],
    [102, 'Exeggcute', 'Grama', 'Psíquico', endereco.removesuffix('model') + 'assets\\\\102.png', 5, 5, 5, 'descrição'],
    [103, 'Exeggutor', 'Grama', 'Psíquico', endereco.removesuffix('model') + 'assets\\\\103.png', 5, 5, 5, 'descrição'],
    [104, 'Cubone', 'Terrestre', 'NULL', endereco.removesuffix('model') + 'assets\\\\104.png', 5, 5, 5, 'descrição'],
    [105, 'Marowak', 'Terrestre', 'NULL', endereco.removesuffix('model') + 'assets\\\\105.png', 5, 5, 5, 'descrição'],
    [106, 'Hitmonlee', 'Lutador', 'NULL', endereco.removesuffix('model') + 'assets\\\\106.png', 5, 5, 5, 'descrição'],
    [107, 'Hitmonchan', 'Lutador', 'NULL', endereco.removesuffix('model') + 'assets\\\\107.png', 5, 5, 5, 'descrição'],
    [108, 'Lickitung', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\108.png', 5, 5, 5, 'descrição'],
    [109, 'Koffing', 'Venenoso', 'NULL', endereco.removesuffix('model') + 'assets\\\\109.png', 5, 5, 5, 'descrição'],
    [110, 'Weezing', 'Venenoso', 'NULL', endereco.removesuffix('model') + 'assets\\\\110.png', 5, 5, 5, 'descrição'],
    [111, 'Rhyhorn', 'Terrestre', 'Pedra', endereco.removesuffix('model') + 'assets\\\\111.png', 5, 5, 5, 'descrição'],
    [112, 'Rhydon', 'Terrestre', 'Pedra', endereco.removesuffix('model') + 'assets\\\\112.png', 5, 5, 5, 'descrição'],
    [113, 'Chansey', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\113.png', 5, 5, 5, 'descrição'],
    [114, 'Tangela', 'Grama', 'NULL', endereco.removesuffix('model') + 'assets\\\\114.png', 5, 5, 5, 'descrição'],
    [115, 'Kangaskhan', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\115.png', 5, 5, 5, 'descrição'],
    [116, 'Horsea', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\116.png', 5, 5, 5, 'descrição'],
    [117, 'Seadra', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\117.png', 5, 5, 5, 'descrição'],
    [118, 'Goldeen', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\118.png', 5, 5, 5, 'descrição'],
    [119, 'Seaking', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\119.png', 5, 5, 5, 'descrição'],
    [120, 'Staryu', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\120.png', 5, 5, 5, 'descrição'],
    [121, 'Starmie', 'Água', 'Psíquico', endereco.removesuffix('model') + 'assets\\\\121.png', 5, 5, 5, 'descrição'],
    [122, 'Mr. Mime', 'Psíquico', 'Fada', endereco.removesuffix('model') + 'assets\\\\122.png', 5, 5, 5, 'descrição'],
    [123, 'Scyther', 'Inseto', 'Voador', endereco.removesuffix('model') + 'assets\\\\123.png', 5, 5, 5, 'descrição'],
    [124, 'Jynx', 'Gelo', 'Psíquico', endereco.removesuffix('model') + 'assets\\\\124.png', 5, 5, 5, 'descrição'],
    [125, 'Electabuzz', 'Elétrico', 'NULL', endereco.removesuffix('model') + 'assets\\\\125.png', 5, 5, 5, 'descrição'],
    [126, 'Magmar', 'Fogo', 'NULL', endereco.removesuffix('model') + 'assets\\\\126.png', 5, 5, 5, 'descrição'],
    [127, 'Pinsir', 'Inseto', 'NULL', endereco.removesuffix('model') + 'assets\\\\127.png', 5, 5, 5, 'descrição'],
    [128, 'Tauros', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\128.png', 5, 5, 5, 'descrição'],
    [129, 'Magikarp', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\129.png', 5, 5, 5, 'descrição'],
    [130, 'Gyarados', 'Água', 'Voador', endereco.removesuffix('model') + 'assets\\\\130.png', 5, 5, 5, 'descrição'],
    [131, 'Lapras', 'Água', 'Gelo', endereco.removesuffix('model') + 'assets\\\\131.png', 5, 5, 5, 'descrição'],
    [132, 'Ditto', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\132.png', 5, 5, 5, 'descrição'],
    [133, 'Eevee', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\133.png', 5, 5, 5, 'descrição'],
    [134, 'Vaporeon', 'Água', 'NULL', endereco.removesuffix('model') + 'assets\\\\134.png', 5, 5, 5, 'descrição'],
    [135, 'Jolteon', 'Elétrico', 'NULL', endereco.removesuffix('model') + 'assets\\\\135.png', 5, 5, 5, 'descrição'],
    [136, 'Flareon', 'Fogo', 'NULL', endereco.removesuffix('model') + 'assets\\\\136.png', 5, 5, 5, 'descrição'],
    [137, 'Porygon', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\137.png', 5, 5, 5, 'descrição'],
    [138, 'Omanyte', 'Pedra', 'Água', endereco.removesuffix('model') + 'assets\\\\138.png', 5, 5, 5, 'descrição'],
    [139, 'Omastar', 'Pedra', 'Água', endereco.removesuffix('model') + 'assets\\\\139.png', 5, 5, 5, 'descrição'],
    [140, 'Kabuto', 'Pedra', 'Água', endereco.removesuffix('model') + 'assets\\\\140.png', 5, 5, 5, 'descrição'],
    [141, 'Kabutops', 'Pedra', 'Água', endereco.removesuffix('model') + 'assets\\\\141.png', 5, 5, 5, 'descrição'],
    [142, 'Aerodactyl', 'Pedra', 'Voador', endereco.removesuffix('model') + 'assets\\\\142.png', 5, 5, 5, 'descrição'],
    [143, 'Snorlax', 'Normal', 'NULL', endereco.removesuffix('model') + 'assets\\\\143.png', 5, 5, 5, 'descrição'],
    [144, 'Articuno', 'Gelo', 'Voador', endereco.removesuffix('model') + 'assets\\\\144.png', 5, 5, 5, 'descrição'],
    [145, 'Zapdos', 'Elétrico', 'Voador', endereco.removesuffix('model') + 'assets\\\\145.png', 5, 5, 5, 'descrição'],
    [146, 'Moltres', 'Fogo', 'Voador', endereco.removesuffix('model') + 'assets\\\\146.png', 5, 5, 5, 'descrição'],
    [147, 'Dratini', 'Dragão', 'NULL', endereco.removesuffix('model') + 'assets\\\\147.png', 5, 5, 5, 'descrição'],
    [148, 'Dragonair', 'Dragão', 'NULL', endereco.removesuffix('model') + 'assets\\\\148.png', 5, 5, 5, 'descrição'],
    [149, 'Dragonite', 'Dragão', 'Voador', endereco.removesuffix('model') + 'assets\\\\149.png', 5, 5, 5, 'descrição'],
    [150, 'Mewtwo', 'Psíquico', 'NULL', endereco.removesuffix('model') + 'assets\\\\150.png', 5, 5, 5, 'descrição'],
    [151, 'Mew', 'Psíquico', 'NULL', endereco.removesuffix('model') + 'assets\\\\151.png', 5, 5, 5, 'descrição']
]

banco = connect(
  host="localhost",
  user="root",
  password="",
  database="Pokedex"
)
cursor = banco.cursor()
for pokemon in pokemons:
    pokemon = tuple(pokemon)
    cursor.execute('insert into tb_pokemons (id, nome, tipo_1, tipo_2, foto, força, defesa, hp, descrição) values (%d, %s, %s, %s, %s, %d, %d, %d, %s);', pokemon)
banco.commit()
cursor.close()
banco.close()
	
