from mysql.connector import connect

pokemons = [
    [1, 'Bulbassauro', 'Grama', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Bulbassauro.png', 5, 5, 5, 'descrição'],
    [2, 'Ivyssauro', 'Grama', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Ivyssauro.png', 5, 5, 5, 'descrição'],
    [3, 'Venussauro', 'Grama', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Venussauro.png', 5, 5, 5, 'descrição'],
    [4, 'Charmander', 'Fogo', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Charmander.png', 5, 5, 5, 'descrição'],
    [5, 'Charmeleon', 'Fogo', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Charmeleon.png', 5, 5, 5, 'descrição'],
    [6, 'Charizard', 'Fogo', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Charizard.png', 5, 5, 5, 'descrição'],
    [7, 'Squirtle', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Squirtle.png', 5, 5, 5, 'descrição'],
    [8, 'Wartortle', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Wartortle.png', 5, 5, 5, 'descrição'],
    [9, 'Blastoise', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Blastoise.png', 5, 5, 5, 'descrição'],
    [10, 'Caterpie', 'Inseto', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Caterpie.png', 5, 5, 5, 'descrição'],
    [11, 'Metapod', 'Inseto', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Metapod.png', 5, 5, 5, 'descrição'],
    [12, 'Butterfree', 'Inseto', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Butterfree.png', 5, 5, 5, 'descrição'],
    [13, 'Weedle', 'Inseto', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Weedle.png', 5, 5, 5, 'descrição'],
    [14, 'Kakuna', 'Inseto', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Kakuna.png', 5, 5, 5, 'descrição'],
    [15, 'Beedrill', 'Inseto', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Beedrill.png', 5, 5, 5, 'descrição'],
    [16, 'Pidgey', 'Normal', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Pidgey.png', 5, 5, 5, 'descrição'],
    [17, 'Pidgeotto', 'Normal', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Pidgeotto.png', 5, 5, 5, 'descrição'],
    [18, 'Pidgeot', 'Normal', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Pidgeot.png', 5, 5, 5, 'descrição'],
    [19, 'Rattata', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Rattata.png', 5, 5, 5, 'descrição'],
    [20, 'Raticate', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Raticate.png', 5, 5, 5, 'descrição'],
    [21, 'Spearow', 'Normal', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Spearow.png', 5, 5, 5, 'descrição'],
    [22, 'Fearow', 'Normal', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Fearow.png', 5, 5, 5, 'descrição'],
    [23, 'Ekans', 'Venenoso', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Ekans.png', 5, 5, 5, 'descrição'],
    [24, 'Arbok', 'Venenoso', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Arbok.png', 5, 5, 5, 'descrição'],
    [25, 'Pikachu', 'Elétrico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Pikachu.png', 5, 5, 5, 'descrição'],
    [26, 'Raichu', 'Elétrico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Raichu.png', 5, 5, 5, 'descrição'],
    [27, 'Sandshrew', 'Terrestre', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Sandshrew.png', 5, 5, 5, 'descrição'],
    [28, 'Sandslash', 'Terrestre', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Sandslash.png', 5, 5, 5, 'descrição'],
    [29, 'Nidoran♀', 'Venenoso', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Nidoran♀.png', 5, 5, 5, 'descrição'],
    [30, 'Nidorina', 'Venenoso', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Nidorina.png', 5, 5, 5, 'descrição'],
    [31, 'Nidoqueen', 'Venenoso', 'Terrestre', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Nidoqueen.png', 5, 5, 5, 'descrição'],
    [32, 'Nidoran♂', 'Venenoso', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Nidoran♂.png', 5, 5, 5, 'descrição'],
    [33, 'Nidorino', 'Venenoso', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Nidorino.png', 5, 5, 5, 'descrição'],
    [34, 'Nidoking', 'Venenoso', 'Terrestre', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Nidoking.png', 5, 5, 5, 'descrição'],
    [35, 'Clefairy', 'Fada', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Clefairy.png', 5, 5, 5, 'descrição'],
    [36, 'Clefable', 'Fada', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Clefable.png', 5, 5, 5, 'descrição'],
    [37, 'Vulpix', 'Fogo', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Vulpix.png', 5, 5, 5, 'descrição'],
    [38, 'Ninetales', 'Fogo', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Ninetales.png', 5, 5, 5, 'descrição'],
    [39, 'Jigglypuff', 'Normal', 'Fada', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Jigglypuff.png', 5, 5, 5, 'descrição'],
    [40, 'Wigglytuff', 'Normal', 'Fada', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Wigglytuff.png', 5, 5, 5, 'descrição'],
    [41, 'Zubat', 'Venenoso', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Zubat.png', 5, 5, 5, 'descrição'],
    [42, 'Golbat', 'Venenoso', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Golbat.png', 5, 5, 5, 'descrição'],
    [43, 'Oddish', 'Grama', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Oddish.png', 5, 5, 5, 'descrição'],
    [44, 'Gloom', 'Grama', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Gloom.png', 5, 5, 5, 'descrição'],
    [45, 'Vileplume', 'Grama', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Vileplume.png', 5, 5, 5, 'descrição'],
    [46, 'Paras', 'Inseto', 'Grama', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Paras.png', 5, 5, 5, 'descrição'],
    [47, 'Parasect', 'Inseto', 'Grama', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Parasect.png', 5, 5, 5, 'descrição'],
    [48, 'Venonat', 'Inseto', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Venonat.png', 5, 5, 5, 'descrição'],
    [49, 'Venomoth', 'Inseto', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Venomoth.png', 5, 5, 5, 'descrição'],
    [50, 'Diglett', 'Terrestre', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Diglett.png', 5, 5, 5, 'descrição'],
    [51, 'Dugtrio', 'Terrestre', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Dugtrio.png', 5, 5, 5, 'descrição'],
    [52, 'Meowth', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Meowth.png', 5, 5, 5, 'descrição'],
    [53, 'Persian', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Persian.png', 5, 5, 5, 'descrição'],
    [54, 'Psyduck', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Psyduck.png', 5, 5, 5, 'descrição'],
    [55, 'Golduck', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Golduck.png', 5, 5, 5, 'descrição'],
    [56, 'Mankey', 'Lutador', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Mankey.png', 5, 5, 5, 'descrição'],
    [57, 'Primeape', 'Lutador', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Primeape.png', 5, 5, 5, 'descrição'],
    [58, 'Growlithe', 'Fogo', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Growlithe.png', 5, 5, 5, 'descrição'],
    [59, 'Arcanine', 'Fogo', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Arcanine.png', 5, 5, 5, 'descrição'],
    [60, 'Poliwag', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Poliwag.png', 5, 5, 5, 'descrição'],
    [61, 'Poliwhirl', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Poliwhirl.png', 5, 5, 5, 'descrição'],
    [62, 'Poliwrath', 'Água', 'Lutador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Poliwrath.png', 5, 5, 5, 'descrição'],
    [63, 'Abra', 'Psíquico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Abra.png', 5, 5, 5, 'descrição'],
    [64, 'Kadabra', 'Psíquico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Kadabra.png', 5, 5, 5, 'descrição'],
    [65, 'Alakazam', 'Psíquico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Alakazam.png', 5, 5, 5, 'descrição'],
    [66, 'Machop', 'Lutador', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Machop.png', 5, 5, 5, 'descrição'],
    [67, 'Machoke', 'Lutador', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Machoke.png', 5, 5, 5, 'descrição'],
    [68, 'Machamp', 'Lutador', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Machamp.png', 5, 5, 5, 'descrição'],
    [69, 'Bellsprout', 'Grama', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Bellsprout.png', 5, 5, 5, 'descrição'],
    [70, 'Weepinbell', 'Grama', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Weepinbell.png', 5, 5, 5, 'descrição'],
    [71, 'Victreebel', 'Grama', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Victreebel.png', 5, 5, 5, 'descrição'],
    [72, 'Tentacool', 'Água', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Tentacool.png', 5, 5, 5, 'descrição'],
    [73, 'Tentacruel', 'Água', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Tentacruel.png', 5, 5, 5, 'descrição'],
    [74, 'Geodude', 'Pedra', 'Terrestre', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Geodude.png', 5, 5, 5, 'descrição'],
    [75, 'Graveler', 'Pedra', 'Terrestre', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Graveler.png', 5, 5, 5, 'descrição'],
    [76, 'Golem', 'Pedra', 'Terrestre', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Golem.png', 5, 5, 5, 'descrição'],
    [77, 'Ponyta', 'Fogo', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Ponyta.png', 5, 5, 5, 'descrição'],
    [78, 'Rapidash', 'Fogo', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Rapidash.png', 5, 5, 5, 'descrição'],
    [79, 'Slowpoke', 'Água', 'Psíquico', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Slowpoke.png', 5, 5, 5, 'descrição'],
    [80, 'Slowbro', 'Água', 'Psíquico', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Slowbro.png', 5, 5, 5, 'descrição'],
    [81, 'Magnemite', 'Elétrico', 'Aço', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Magnemite.png', 5, 5, 5, 'descrição'],
    [82, 'Magneton', 'Elétrico', 'Aço', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Magneton.png', 5, 5, 5, 'descrição'],
    [83, '083Farfetch d', 'Farfetch', 'Normal Voador', 'd', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\083Farfetch d.png', 5, 5, 5, 'descrição'],
    [84, 'Doduo', 'Normal', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Doduo.png', 5, 5, 5, 'descrição'],
    [85, 'Dodrio', 'Normal', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Dodrio.png', 5, 5, 5, 'descrição'],
    [86, 'Seel', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Seel.png', 5, 5, 5, 'descrição'],
    [87, 'Dewgong', 'Água', 'Gelo', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Dewgong.png', 5, 5, 5, 'descrição'],
    [88, 'Grimer', 'Venenoso', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Grimer.png', 5, 5, 5, 'descrição'],
    [89, 'Muk', 'Venenoso', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Muk.png', 5, 5, 5, 'descrição'],
    [90, 'Shellder', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Shellder.png', 5, 5, 5, 'descrição'],
    [91, 'Cloyster', 'Água', 'Gelo', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Cloyster.png', 5, 5, 5, 'descrição'],
    [92, 'Gastly', 'Fantasma', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Gastly.png', 5, 5, 5, 'descrição'],
    [93, 'Haunter', 'Fantasma', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Haunter.png', 5, 5, 5, 'descrição'],
    [94, 'Gengar', 'Fantasma', 'Venenoso', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Gengar.png', 5, 5, 5, 'descrição'],
    [95, 'Onix', 'Pedra', 'Terrestre', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Onix.png', 5, 5, 5, 'descrição'],
    [96, 'Drowzee', 'Psíquico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Drowzee.png', 5, 5, 5, 'descrição'],
    [97, 'Hypno', 'Psíquico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Hypno.png', 5, 5, 5, 'descrição'],
    [98, 'Krabby', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Krabby.png', 5, 5, 5, 'descrição'],
    [99, 'Kingler', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Kingler.png', 5, 5, 5, 'descrição'],
    [100, 'Voltorb', 'Elétrico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Voltorb.png', 5, 5, 5, 'descrição'],
    [101, 'Electrode', 'Elétrico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Electrode.png', 5, 5, 5, 'descrição'],
    [102, 'Exeggcute', 'Grama', 'Psíquico', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Exeggcute.png', 5, 5, 5, 'descrição'],
    [103, 'Exeggutor', 'Grama', 'Psíquico', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Exeggutor.png', 5, 5, 5, 'descrição'],
    [104, 'Cubone', 'Terrestre', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Cubone.png', 5, 5, 5, 'descrição'],
    [105, 'Marowak', 'Terrestre', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Marowak.png', 5, 5, 5, 'descrição'],
    [106, 'Hitmonlee', 'Lutador', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Hitmonlee.png', 5, 5, 5, 'descrição'],
    [107, 'Hitmonchan', 'Lutador', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Hitmonchan.png', 5, 5, 5, 'descrição'],
    [108, 'Lickitung', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Lickitung.png', 5, 5, 5, 'descrição'],
    [109, 'Koffing', 'Venenoso', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Koffing.png', 5, 5, 5, 'descrição'],
    [110, 'Weezing', 'Venenoso', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Weezing.png', 5, 5, 5, 'descrição'],
    [111, 'Rhyhorn', 'Terrestre', 'Pedra', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Rhyhorn.png', 5, 5, 5, 'descrição'],
    [112, 'Rhydon', 'Terrestre', 'Pedra', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Rhydon.png', 5, 5, 5, 'descrição'],
    [113, 'Chansey', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Chansey.png', 5, 5, 5, 'descrição'],
    [114, 'Tangela', 'Grama', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Tangela.png', 5, 5, 5, 'descrição'],
    [115, 'Kangaskhan', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Kangaskhan.png', 5, 5, 5, 'descrição'],
    [116, 'Horsea', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Horsea.png', 5, 5, 5, 'descrição'],
    [117, 'Seadra', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Seadra.png', 5, 5, 5, 'descrição'],
    [118, 'Goldeen', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Goldeen.png', 5, 5, 5, 'descrição'],
    [119, 'Seaking', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Seaking.png', 5, 5, 5, 'descrição'],
    [120, 'Staryu', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Staryu.png', 5, 5, 5, 'descrição'],
    [121, 'Starmie', 'Água', 'Psíquico', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Starmie.png', 5, 5, 5, 'descrição'],
    [122, 'Mr. Mime', 'Psíquico', 'Fada', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Mr. Mime.png', 5, 5, 5, 'descrição'],
    [123, 'Scyther', 'Inseto', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Scyther.png', 5, 5, 5, 'descrição'],
    [124, 'Jynx', 'Gelo', 'Psíquico', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Jynx.png', 5, 5, 5, 'descrição'],
    [125, 'Electabuzz', 'Elétrico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Electabuzz.png', 5, 5, 5, 'descrição'],
    [126, 'Magmar', 'Fogo', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Magmar.png', 5, 5, 5, 'descrição'],
    [127, 'Pinsir', 'Inseto', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Pinsir.png', 5, 5, 5, 'descrição'],
    [128, 'Tauros', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Tauros.png', 5, 5, 5, 'descrição'],
    [129, 'Magikarp', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Magikarp.png', 5, 5, 5, 'descrição'],
    [130, 'Gyarados', 'Água', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Gyarados.png', 5, 5, 5, 'descrição'],
    [131, 'Lapras', 'Água', 'Gelo', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Lapras.png', 5, 5, 5, 'descrição'],
    [132, 'Ditto', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Ditto.png', 5, 5, 5, 'descrição'],
    [133, 'Eevee', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Eevee.png', 5, 5, 5, 'descrição'],
    [134, 'Vaporeon', 'Água', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Vaporeon.png', 5, 5, 5, 'descrição'],
    [135, 'Jolteon', 'Elétrico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Jolteon.png', 5, 5, 5, 'descrição'],
    [136, 'Flareon', 'Fogo', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Flareon.png', 5, 5, 5, 'descrição'],
    [137, 'Porygon', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Porygon.png', 5, 5, 5, 'descrição'],
    [138, 'Omanyte', 'Pedra', 'Água', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Omanyte.png', 5, 5, 5, 'descrição'],
    [139, 'Omastar', 'Pedra', 'Água', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Omastar.png', 5, 5, 5, 'descrição'],
    [140, 'Kabuto', 'Pedra', 'Água', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Kabuto.png', 5, 5, 5, 'descrição'],
    [141, 'Kabutops', 'Pedra', 'Água', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Kabutops.png', 5, 5, 5, 'descrição'],
    [142, 'Aerodactyl', 'Pedra', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Aerodactyl.png', 5, 5, 5, 'descrição'],
    [143, 'Snorlax', 'Normal', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Snorlax.png', 5, 5, 5, 'descrição'],
    [144, 'Articuno', 'Gelo', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Articuno.png', 5, 5, 5, 'descrição'],
    [145, 'Zapdos', 'Elétrico', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Zapdos.png', 5, 5, 5, 'descrição'],
    [146, 'Moltres', 'Fogo', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Moltres.png', 5, 5, 5, 'descrição'],
    [147, 'Dratini', 'Dragão', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Dratini.png', 5, 5, 5, 'descrição'],
    [148, 'Dragonair', 'Dragão', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Dragonair.png', 5, 5, 5, 'descrição'],
    [149, 'Dragonite', 'Dragão', 'Voador', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Dragonite.png', 5, 5, 5, 'descrição'],
    [150, 'Mewtwo', 'Psíquico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Mewtwo.png', 5, 5, 5, 'descrição'],
    [151, 'Mew', 'Psíquico', 'NULL', 'C:\\\\User\\\\Aluno\\\\Downloads\\\\fotos_pokemons\\\\Mew.png', 5, 5, 5, 'descrição']

]
banco = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="Pokedex"
)
cursor = banco.cursor()
for pokemon in pokemons:
	pokemon = tuple(pokemon)
	cursor.execute('insert into tb_pokemons (id, nome, tipo_1, tipo_2, foto, força, defesa, hp, descrição) values (%d, %s, %s, %s, %s, %d, %d, %d, %s);', pokemon)
banco.commit()
cursor.close()
banco.close()
	
